"""
MetricFlow — Realistic B2B Seed Data Generator
Generates SQL INSERT statements for demo data.
Run: python seed_data.py > seed.sql
Then paste seed.sql into Supabase SQL Editor.

Requires: pip install faker
"""

import random
import uuid
from datetime import date, timedelta
from faker import Faker

fake = Faker("ro_RO")
random.seed(42)

# ─── Config ──────────────────────────────────────────────────────────────────
NUM_COMPANIES  = 30
NUM_CONTACTS   = 60
NUM_PRODUCTS   = 20
NUM_ORDERS     = 120
ADMIN_USER_ID  = "6f6eaf39-4fae-4d82-9c9e-5edaf0065da5"  # paste from Supabase Auth dashboard

# ─── Reference data ───────────────────────────────────────────────────────────
INDUSTRIES = ["Technology", "Manufacturing", "Retail", "Healthcare", "Finance",
               "Logistics", "Energy", "Consulting", "Education", "Real Estate"]
COUNTRIES  = ["Romania", "Romania", "Romania", "Germany", "France", "Hungary", "Bulgaria"]
TIERS      = ["enterprise"] * 5 + ["mid_market"] * 10 + ["smb"] * 15
CATEGORIES = ["software", "hardware", "services", "consulting", "support"]
STATUSES   = ["draft", "pending", "confirmed", "processing", "shipped", "delivered", "cancelled"]
STATUS_WEIGHTS = [5, 10, 15, 15, 15, 35, 5]

PRODUCT_DATA = [
    ("ERP Suite Pro",         "SW-001", "software",    14999),
    ("CRM Enterprise",        "SW-002", "software",     8999),
    ("Data Analytics Module", "SW-003", "software",     4999),
    ("API Gateway License",   "SW-004", "software",     2999),
    ("Server Rack 2U",        "HW-001", "hardware",     3500),
    ("NAS Storage 40TB",      "HW-002", "hardware",     5200),
    ("Network Switch 48p",    "HW-003", "hardware",     1800),
    ("Laptop Fleet (10x)",    "HW-004", "hardware",    12000),
    ("Implementation Service","SV-001", "services",     6000),
    ("Data Migration",        "SV-002", "services",     4500),
    ("System Integration",    "SV-003", "services",     8000),
    ("Cloud Setup",           "SV-004", "services",     3000),
    ("Strategy Consulting",   "CO-001", "consulting",   9000),
    ("Digital Transform.",    "CO-002", "consulting",  15000),
    ("Process Audit",         "CO-003", "consulting",   5500),
    ("24/7 Support Gold",     "SP-001", "support",      3600),
    ("Support Silver",        "SP-002", "support",      1800),
    ("SLA Enterprise",        "SP-003", "support",      7200),
    ("Training Package",      "SP-004", "support",      2400),
    ("Security Audit",        "SP-005", "support",      4800),
]

def uid(): return str(uuid.uuid4())
def esc(s): return s.replace("'", "''") if s else ""

print("-- MetricFlow Seed Data")
print("-- Generated by seed_data.py\n")

print("-- USER PROFILES")
print(f"INSERT INTO public.user_profiles (id, email, full_name, role) VALUES ('{ADMIN_USER_ID}', 'admin@metricflow.com', 'Admin User', 'admin') ON CONFLICT (id) DO NOTHING;\n")

print("-- RESET DATA")
print("TRUNCATE TABLE public.order_items CASCADE;")
print("TRUNCATE TABLE public.orders CASCADE;")
print("TRUNCATE TABLE public.contacts CASCADE;")
print("TRUNCATE TABLE public.companies CASCADE;")
print("TRUNCATE TABLE public.products CASCADE;\n")

# ─── Products ─────────────────────────────────────────────────────────────────
product_ids = [uid() for _ in PRODUCT_DATA]
print("-- PRODUCTS")
for pid, (name, sku, cat, price) in zip(product_ids, PRODUCT_DATA):
    stock = random.randint(0, 200)
    print(f"INSERT INTO public.products (id, name, sku, category, unit_price, stock_qty, is_active) "
          f"VALUES ('{pid}', '{esc(name)}', '{sku}', '{cat}', {price}, {stock}, true) ON CONFLICT (id) DO NOTHING;")

print()

# ─── Companies ────────────────────────────────────────────────────────────────
company_ids = [uid() for _ in range(NUM_COMPANIES)]
print("-- COMPANIES")
random.shuffle(TIERS)
for cid, tier in zip(company_ids, TIERS):
    name    = fake.company()
    ind     = random.choice(INDUSTRIES)
    country = random.choice(COUNTRIES)
    city    = fake.city()
    rev     = random.randint(500_000, 50_000_000) if tier == "enterprise" else \
              random.randint(100_000, 5_000_000)  if tier == "mid_market" else \
              random.randint(20_000, 500_000)
    emp     = random.randint(200, 5000) if tier == "enterprise" else \
              random.randint(20, 300)   if tier == "mid_market" else \
              random.randint(2, 50)
    print(f"INSERT INTO public.companies (id, name, industry, country, city, tier, annual_revenue, employee_count, created_by) "
          f"VALUES ('{cid}', '{esc(name)}', '{ind}', '{esc(country)}', '{esc(city)}', '{tier}', {rev}, {emp}, '{ADMIN_USER_ID}') ON CONFLICT (id) DO NOTHING;")

print()

# ─── Contacts ─────────────────────────────────────────────────────────────────
TITLES = ["CEO", "CFO", "CTO", "VP Sales", "Procurement Manager",
          "IT Director", "Operations Manager", "Account Manager"]
print("-- CONTACTS")
for _ in range(NUM_CONTACTS):
    cid2  = uid()
    comp  = random.choice(company_ids)
    name  = fake.name()
    email = fake.email()
    phone = fake.phone_number()
    title = random.choice(TITLES)
    is_p  = "true" if random.random() < 0.3 else "false"
    print(f"INSERT INTO public.contacts (id, company_id, full_name, email, phone, job_title, is_primary) "
          f"VALUES ('{cid2}', '{comp}', '{esc(name)}', '{esc(email)}', '{esc(phone)}', '{title}', {is_p}) ON CONFLICT (id) DO NOTHING;")

print()

# ─── Orders ───────────────────────────────────────────────────────────────────
print("-- ORDERS")
order_ids = []
start_date = date.today() - timedelta(days=365)
for i in range(NUM_ORDERS):
    oid      = uid()
    order_ids.append(oid)
    comp     = random.choice(company_ids)
    status   = random.choices(STATUSES, STATUS_WEIGHTS)[0]
    days_ago = random.randint(0, 365)
    ord_date = (date.today() - timedelta(days=days_ago)).isoformat()
    del_date = (date.today() - timedelta(days=days_ago - random.randint(7, 30))).isoformat()
    num      = f"ORD-{str(i+1001)}"
    print(f"INSERT INTO public.orders (id, order_number, company_id, assigned_to, status, order_date, expected_delivery) "
          f"VALUES ('{oid}', '{num}', '{comp}', '{ADMIN_USER_ID}', '{status}', '{ord_date}', '{del_date}') ON CONFLICT (id) DO NOTHING;")

print()

# ─── Order Items ──────────────────────────────────────────────────────────────
print("-- ORDER ITEMS (trigger will auto-update order totals)")
for oid in order_ids:
    num_items = random.randint(1, 4)
    chosen = random.sample(list(zip(product_ids, PRODUCT_DATA)), num_items)
    for pid, (_, _, _, base_price) in chosen:
        qty   = random.randint(1, 10)
        price = round(base_price * random.uniform(0.9, 1.1), 2)
        print(f"INSERT INTO public.order_items (id, order_id, product_id, quantity, unit_price) "
              f"VALUES ('{uid()}', '{oid}', '{pid}', {qty}, {price}) ON CONFLICT (id) DO NOTHING;")

print("\n-- Seed complete. Refresh your dashboard!")
